import Foundation
import PDFKit
import SwiftUI
import UIKit

struct ExportService {
    /// RFC-4180 CSV of all items.
    func makeCSV(items: [Item]) -> Data {
        var rows: [String] = ["name,brand,category,merchant,purchaseDate,priceMinor,currencyCode,serialNumber,orderNumber"]
        let iso = ISO8601DateFormatter()
        for it in items {
            rows.append([
                csvField(it.name), csvField(it.brand), csvField(it.category.rawValue),
                csvField(it.merchant), csvField(iso.string(from: it.purchaseDate)),
                it.priceMinor.map(String.init) ?? "", csvField(it.currencyCode),
                csvField(it.serialNumber), csvField(it.orderNumber)
            ].joined(separator: ","))
        }
        return rows.joined(separator: "\r\n").data(using: .utf8) ?? Data()
    }

    func csvField(_ s: String) -> String {
        if s.contains(where: { $0 == "," || $0 == "\"" || $0 == "\n" || $0 == "\r" }) {
            return "\"" + s.replacingOccurrences(of: "\"", with: "\"\"") + "\""
        }
        return s
    }

    /// Claim Pack PDF for one item.
    @MainActor
    func makeClaimPackPDF(item: Item) -> Data {
        let view = ClaimPackView(item: item)
        let renderer = ImageRenderer(content: view)
        renderer.proposedSize = .init(width: 612, height: 792)
        guard let image = renderer.uiImage else { return Data() }
        let pdfRenderer = UIGraphicsPDFRenderer(bounds: CGRect(origin: .zero, size: image.size))
        return pdfRenderer.pdfData { ctx in
            ctx.beginPage()
            image.draw(at: .zero)
        }
    }
}

struct ClaimPackView: View {
    let item: Item
    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text(item.name).font(.largeTitle.bold())
            Text([item.brand, item.merchant].filter { !$0.isEmpty }.joined(separator: " · "))
            if !item.serialNumber.isEmpty { Text("Serial: \(item.serialNumber)") }
            Text("Purchased: \(item.purchaseDate.formatted(date: .abbreviated, time: .omitted))")
            if let price = item.priceMinor {
                let major = Double(price) / 100.0
                Text("Price: \(major.formatted(.currency(code: item.currencyCode)))")
            }
            ForEach(item.coverages ?? [], id: \.id) { c in
                HStack {
                    Text(c.kind.label)
                    Spacer()
                    Text(c.endDate.formatted(date: .abbreviated, time: .omitted))
                }
            }
            Spacer()
            Text("Generated by Ownwise").font(.caption).foregroundStyle(.secondary)
        }
        .padding(40)
        .frame(width: 612, alignment: .leading)
        .background(Color.white)
    }
}
